/**
 * Export a monthly summary report as PDF using browser's print dialog.
 * No extra libraries needed — generates a styled HTML page and triggers print.
 */
export function exportPDF(transactions, budgets, month, year) {
  const monthName = new Date(year, month, 1).toLocaleString('default', { month: 'long', year: 'numeric' });
  const txs = transactions.filter(t => {
    const d = new Date(t.date);
    return d.getMonth() === month && d.getFullYear() === year;
  });

  const totalIncome = txs.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0);
  const totalExpense = txs.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const fmt = n => '₹' + Math.round(n).toLocaleString('en-IN');

  // Category breakdown
  const catMap = {};
  txs.filter(t => t.type === 'expense').forEach(t => { catMap[t.category] = (catMap[t.category] || 0) + t.amount; });
  const catRows = Object.entries(catMap).sort((a, b) => b[1] - a[1]);

  const txRows = [...txs].sort((a, b) => new Date(b.date) - new Date(a.date));

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>FinFlow Report – ${monthName}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, 'Segoe UI', sans-serif; font-size: 13px; color: #1a1d23; padding: 32px; }
    h1 { font-size: 22px; font-weight: 700; color: #4CAF50; margin-bottom: 4px; }
    .sub { font-size: 13px; color: #888; margin-bottom: 24px; }
    .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 24px; }
    .stat { border: 1px solid #e8eaee; border-radius: 10px; padding: 14px; }
    .stat-label { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; }
    .stat-val { font-size: 20px; font-weight: 700; }
    .green { color: #4CAF50; } .red { color: #FF7043; } .blue { color: #2196F3; }
    h2 { font-size: 14px; font-weight: 600; margin-bottom: 10px; color: #333; border-bottom: 1px solid #eee; padding-bottom: 6px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { text-align: left; font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 0.04em; padding: 6px 8px; border-bottom: 2px solid #eee; }
    td { padding: 8px 8px; border-bottom: 1px solid #f2f2f2; font-size: 13px; }
    tr:last-child td { border-bottom: none; }
    .income { color: #4CAF50; font-weight: 600; }
    .expense { color: #FF7043; font-weight: 600; }
    .footer { font-size: 11px; color: #bbb; text-align: center; margin-top: 32px; }
    .badge { display: inline-block; padding: 2px 7px; border-radius: 20px; font-size: 11px; font-weight: 600; }
    .badge-income { background: #e8f5e9; color: #388E3C; }
    .badge-expense { background: #fbe9e7; color: #bf360c; }
    @media print { body { padding: 16px; } }
  </style>
</head>
<body>
  <h1>FinFlow</h1>
  <div class="sub">Financial Report · ${monthName}</div>

  <div class="summary">
    <div class="stat"><div class="stat-label">Total Income</div><div class="stat-val green">${fmt(totalIncome)}</div></div>
    <div class="stat"><div class="stat-label">Total Expenses</div><div class="stat-val red">${fmt(totalExpense)}</div></div>
    <div class="stat"><div class="stat-label">Net Savings</div><div class="stat-val ${totalIncome - totalExpense >= 0 ? 'blue' : 'red'}">${fmt(totalIncome - totalExpense)}</div></div>
  </div>

  <h2>Expense by Category</h2>
  <table>
    <thead><tr><th>Category</th><th>Amount</th><th>% of Total</th></tr></thead>
    <tbody>
      ${catRows.map(([cat, amt]) => `<tr><td>${cat}</td><td class="expense">${fmt(amt)}</td><td>${totalExpense > 0 ? Math.round(amt / totalExpense * 100) : 0}%</td></tr>`).join('')}
    </tbody>
  </table>

  ${budgets.total > 0 ? `
  <h2>Budget Summary</h2>
  <table>
    <thead><tr><th>Category</th><th>Spent</th><th>Budget</th><th>Status</th></tr></thead>
    <tbody>
      ${Object.entries(budgets.cats).map(([cat, limit]) => {
        const spent = catMap[cat] || 0;
        const pct = Math.round(spent / limit * 100);
        return `<tr><td>${cat}</td><td>${fmt(spent)}</td><td>${fmt(limit)}</td><td>${pct >= 100 ? '🔴' : pct >= 80 ? '🟡' : '🟢'} ${pct}%</td></tr>`;
      }).join('')}
    </tbody>
  </table>` : ''}

  <h2>All Transactions (${txRows.length})</h2>
  <table>
    <thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Type</th><th>Amount</th></tr></thead>
    <tbody>
      ${txRows.map(t => `
        <tr>
          <td>${t.date}</td>
          <td>${t.desc || t.category}</td>
          <td>${t.category}</td>
          <td><span class="badge badge-${t.type}">${t.type}</span></td>
          <td class="${t.type}">${t.type === 'income' ? '+' : '−'}${fmt(t.amount)}</td>
        </tr>`).join('')}
    </tbody>
  </table>

  <div class="footer">Generated by FinFlow · ${new Date().toLocaleString()}</div>
</body>
</html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => { win.print(); }, 400);
}
